### ISSUE TITLE
UI Clipping when Uploading files to Mega Mess. 

### ISSUE THREAD

**Issue by dagweg** [Kinfe123/MegaMess#27]
![image](https://github.com/Kinfe123/MegaMess/assets/90281138/7da61319-cc22-4fa2-8a26-ce498dfde168)

There is a clipping going on when I upload lots of files. Essentially, I can't give title & description for it.

**Comment by Kinfe123** [comment]
@dagweg  Thanks for taking a look at. The thing is since the foundation of the ui is from shadcn , most of modal based ui do have a an overflow-hidden so that you wont get to see the thing when it goes out of the min-height, you can propose your own solution and i am happy to go through your changes
